# -*- coding: utf-8 -*-
"""Web Scraping with BeautifulSoup.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/gist/anursen/734a07f0bf06331a45b108f85366757f/web-scraping-with-beautifulsoup.ipynb
"""

#importing libraries
from bs4 import BeautifulSoup
import requests

#requesting the website
soup = BeautifulSoup()
link = 'http://www.mintybuy.com/'
page = requests.get(link)
soup = BeautifulSoup(page.content, 'html.parser')
#print(soup.prettify())

#defining new empty list for data appending
items = []
price = []
sku_variant = []
variant = []
sku = []
#importing needed variables from the soup object
items = [i.get_text() for i in soup.find_all('h7')]
price = [i.get_text().replace('\n$ ','').replace('\n','') for i in soup.find_all('h4')]
sku_variant = [i.get_text().replace('\n$ ','').replace('\n','') for i in soup.find_all('h5')]
variant = sku_variant[::2]
sku = sku_variant[1::2]
del sku_variant

#importing variables to Pandas Data Frame
import pandas as pd
df = pd.DataFrame(sku)
df.columns = ['sku']
df['title'] = items
df['variant'] = variant
df['price'] = price

#Exporting data to csv
df.to_csv()